# This is a basic workflow to help you get started with Actions
name: Tests

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  - push
  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  type-checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: tests
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
      # Runs a set of commands using the runners shell
      - name: Run type checks
        run: |
          npm ci
          npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
